# Generated by Django 4.1.4 on 2022-12-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Levelone_assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn1', models.CharField(max_length=20)),
                ('qn2', models.CharField(max_length=20)),
                ('qn3', models.CharField(max_length=20)),
                ('qn4', models.CharField(max_length=20)),
                ('qn5', models.CharField(max_length=50)),
                ('qn6', models.CharField(max_length=20)),
                ('qn7', models.CharField(max_length=20)),
                ('qn8', models.CharField(max_length=20)),
                ('qn9', models.CharField(max_length=20)),
                ('qn10', models.CharField(max_length=20)),
            ],
        ),
    ]
