# Generated by Django 4.1.4 on 2022-12-27 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn10',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn2',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn3',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn4',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn5',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn6',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn7',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn8',
        ),
        migrations.RemoveField(
            model_name='levelone_assessment',
            name='qn9',
        ),
        migrations.AlterField(
            model_name='levelone_assessment',
            name='qn1',
            field=models.IntegerField(),
        ),
    ]
